### ISSUE TITLE
[FULLCUSTOM] ページをまたいでパーツの位置を変更できるようにしたい

### ISSUE THREAD

**Issue by Yuya-Fukano** [sony/huis-ui-creator#1]
現在は、リモコン編集画面にて UI パーツをページをまたいで位置を変更することができない。
現状、異なるページに UI パーツを移動する際、
1. パーツの削除
2. 別のページでパーツを新規追加
3.  2. のボタンのプロパティーを手動編集で、1. で削除したボタンのプロパティーのものにする

という手順を踏む必要があり、面倒。

**Comment by SasakiMotoki** [comment]
2017.02.23現在 ページをまたいで、アイテム(ボタン、ラベル、画像)を配置できることを確認しました。

**Comment by Kosuke-Mita** [comment]
解決済みですので、Closeさせていただきます。
