### ISSUE TITLE
ボタンのアクションを「長押し」のみ設定すると、動作しない

### ISSUE THREAD

**Issue by TE-MotokiSasaki** [sony/huis-ui-creator#11]
ボタンのアクションに「長押し」のみ設定すると、信号がでません。
「タッチ」と「長押し」や「上半分をタッチ」と「長押し」など複数登録すると有効になるようです。
このIssueはHUIS UI CREATOR の問題ではなく、 HUISのファームウェアのバグだと考えられます。

**Comment by SasakiMotoki** [comment]
本issueは、2017.02.23のレポジトリと、HUIS-100RC ver. 4.1.0では再現しないことを確認しました。
CLOSEいたします。
