### ISSUE TITLE
編集したボタン と ラベル(ボタンでないテキスト) のテキスト位置、大きさが「HUIS」に反映されない

### ISSUE THREAD

**Issue by TE-MotokiSasaki** [sony/huis-ui-creator#12]
テキストボタンやラベルを作って、HUIS上に同期しても見た目が変わってしまいます。
テキストサイズが変更されないように見えます。
このIssueはHUIS UI CREATOR の問題ではなく、 HUISのファームウェアのバグだと考えられます。

**Comment by SasakiMotoki** [comment]
2017.02.23現在のレポジトリでは、テキストボタン・ラベルの大きさを変更すると、HUIS-100RC上でも大きさの変更が反映されていることを確認しました。このIssueはCLOSEします。
