### ISSUE TITLE
1個のボタンに複数のアクションを設定すると、アクションによってはヒットエリアが重なる為、複数の信号が送信される

### ISSUE THREAD

**Issue by TE-MotokiSasaki** [sony/huis-ui-creator#13]
ボタンのアクションに「上半分をタッチ」と「タッチ」それぞれに信号を登録し、HUIS上でボタンの上半分をタッチすると２つ信号がでてしまいます。
このIssueはHUIS UI CREATOR の問題ではなく、 HUISのファームウェアのバグだと考えられます。

**Comment by SasakiMotoki** [comment]
2017.02.23 現在、 「上半分をタッチ」と「タッチ」は同時に設定できないようになっています。そのため、CLOSEします。
