### ISSUE TITLE
UI CREATORで作ったボタンは、リモコン学習できない。

### ISSUE THREAD

**Issue by CALLTENCHO** [sony/huis-ui-creator#18]
UI CREATORで作ったボタンは、リモコン学習できない。そのため、いったん、HUIS本体で作ったボタンに学習させ、それを、UI CREATORでコピーペーストで配置するしかない。

**Comment by Yuya-Fukano** [comment]
ご指摘ありがとうございます。

現時点では、HUIS UI CREATOR で作成したボタンを、HUIS REMOTE CONTROLLER で学習させることはできないようになっております。
今後、HUIS UI CREATOR をよりよいものにするために、頂いたご意見を参考にし、
「HUIS UI CREATOR」と「HUIS REMOTE CONTROLLERの学習」との連携をよりスムーズにできるよう対応を検討させていただきます。

**Comment by SasakiMotoki** [comment]
大変お待たせいたしました。
本日リリースの 
・HUIS UI CREATOR version 3.0.0 
・HUIS REMOTE CONTROLLER version 4.1.0

において
HUIS UI CREATORで作成したリモコンのボタンも学習可能になりました。

**Comment by CALLTENCHO** [comment]
今回のアップデートでついに実現したんですね！
ありがとうございます。

**Comment by SasakiMotoki** [comment]
はい。
長らくお待たせいたしました。
こちらのレポジトリにも更新内容をマージいたしますので、少々おまちください。

**Comment by SasakiMotoki** [comment]
長らくお待たせいたしました。本レポジトリにおいても、「HUIS UI CREATORで作成したリモコン」においても、再学習が可能となりました。

使い勝手の向上のための御指摘、ありがとうございました。
改めまして、お礼申し上げます。

**Comment by Kosuke-Mita** [comment]
解決済みですので、Closeさせていただきます。
