### ISSUE TITLE
[FULLCUSTOM] グリッドのサイズについて

### ISSUE THREAD

**Issue by Yuya-Fukano** [sony/huis-ui-creator#6]
現在、グリッドのサイズを [4px, 8px, 16px, 32px, 64px] から選べるが、 標準的なボタンのサイズが 100px × 70px で、これらのグリッドサイズでは表現できない大きさである。

何かよいグリッドサイズはないものか。

**Comment by Kosuke-Mita** [comment]
現在の仕様に沿っていないのでCloseします。
